version: '3'

services:
  dbkc:
    image: postgres:12.15-alpine3.18
    container_name: kc-db
    restart: always
    user: 1000:1000
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_PORT=5433
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - 5433:5432
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_DB_URL_HOST=dbkc
      - KC_DB_URL_PORT=5432
      - KC_DB_SCHEMA=public
    ports:
      - 8080:8080
    command: start-dev
    depends_on:
      - dbkc